DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TYPE IF EXISTS ROLE_NAME;
DROP TABLE IF EXISTS hotel_amenities;
DROP TABLE IF EXISTS hotel_rooms;
DROP TABLE IF EXISTS hotels;
DROP TABLE IF EXISTS hotel_addresses;